### ISSUE TITLE
Coquilles dans les blocs de code

### ISSUE THREAD

**Issue by Aakodal** [ES-Community/Code-of-conduct#104]
J'ai remarqué certaines "coquilles" dans les blocs de code qui sont surtout de l'ordre de la consistance du coding style :
- Sur les 4 strings non template strings dans les deux premiers blocs, vous alternez single quotes et double quotes
- Dans le bloc sur le code de conduite, vous avez des espaces en trop après la parenthèse du join et avant la virgule des arguments
- Dans le bloc sur les invitations, il manque l'espace avant la virgule dans les arguments du `addEventListener`. Par ailleurs, mais ça c'est discutable, la forme `function(arg) {}` pour un callback me semble un peu désuète depuis ES2015 et les arrow functions
- Dans le bloc sur les salons, le `console.log`, en plus de manquer le point-virgule final présent partout ailleurs, n'est pas correct (cf #102)

P-S : je ne fais pas de PR étant donné que pour certaines "coquilles", ça dépend du coding style voulu de base, je ne vais donc pas imposer le mien.

**Comment by Mesteery** [comment]
Je suis d'accord. J'avais aussi remarquer ces "coquilles".
Je propose :
```js
const you = ESCommunity.currentUser();

if (!you.hasReadCodeOfConduct) {
  throw new Error('Merci de lire le code de conduite !');
}
you.setChannel('Presentation');
you.write('... Hello world !');
```
```js
fs.createReadStream(path.join(__dirname, 'code_of_conduct.txt')).pipe(process.stdout);
```
```js
for await (const line of ESCommunity.prohibedBehaviors()) {
  console.log(`- ${line}`);
}
```
```js
document.getElementById('discordInvitation').addEventListener('click', (e) => {
  e.preventDefault(); 
  ESCommunity.invite(user);
});
```
```js
const channels = ESCommunity.getChannels();
for (const [name, description] of channels) {
  console.log(`- \`#${name}\` - ${description}`);
}
```

**Comment by Purexo** [comment]
Bonjour,

Je clos cette issue qui est très vielle, il me semble que le CoC à subit de grosse révisions depuis.
Au besoin il ne faut vraiment pas hésiter à faire des PR, le CoC est un document collaboratif, conçu pour et par la communauté.

Si il y a des sujets à débats comme le coding style, ils pourront être débattu dans la PR
