### ISSUE TITLE
Salon stats

### ISSUE THREAD

**Issue by Mesteery** [ES-Community/Code-of-conduct#105]
Je propose un salon `#statistiques`, qui serait remplit au fur et à mesure par le [bot](https://github.com/ES-Community/bot) automatiquement, par exemple tout les mois.

**Comment by Xstoudi** [comment]
Imo, si tu veux PR il va falloir étayer un peu tout ça.

**Comment by Mesteery** [comment]
C'est-à-dire ?

**Comment by Xstoudi** [comment]
Quels stats ?
Où stock-t-on ?
Qu'est-ce qu'on en fait ?

Je pense qu'une proposal complète devrait être discutée sur le bot avant même de penser à rajouter un channel de stats ^^

**Comment by Mesteery** [comment]
Quand j'y pense c'est peut-être inutile.
J'ai vu que des fois quelques statistiques étaient balancées sur le serveur (par exemple, le nombres de lien dans #liens par Fraxken).
Donc, peut-être des statistiques générales, journalières, mensuels, (annuelles ?) : le nombres de messages, de liens, de réactions (exemples), de join/leaves.
![Screenshot_20210204-172439_Discord](https://user-images.githubusercontent.com/48163546/106923222-24d3de80-670e-11eb-8d80-2de12db33e7c.jpg)
*Ça me fait penser à ça sur NaN.*

Comme je l'ai déjà dit, cela peut paraître complètement inutile et je comprendrai totalement (je le pense aussi).

**Comment by Purexo** [comment]
déplacé ici : https://github.com/ES-Community/bot/issues/49
