### ISSUE TITLE
Mentionner le bot dans le CoC

### ISSUE THREAD

**Issue by targos** [ES-Community/Code-of-conduct#114]
https://github.com/ES-Community/bot/pull/71#issuecomment-1287670639

Je pense que ça ne ferait pas de mal de mettre une petite section pour parler du bot, en expliquant que toute la communauté peut contribuer et qu'il suffit de "watch" le repo (ou de suivre le channel `#logs` pour savoir ce qui s'y passe).

**Comment by Purexo** [comment]
#111 ça pourrait aussi être ajouté dans le canal de règle qui servira d'accueil des nouveaux arrivants
