### ISSUE TITLE
Unification avec la communauté slack FranceJS

### ISSUE THREAD

**Issue by fraxken** [ES-Community/Code-of-conduct#115]
Hello 👋

Je me permets d'ouvrir cette issue de **ma propre initiative** pour lancer le sujet d'une unification avec la **communauté Slack FranceJS** (Je vise ici principalement le slack lui-même, sans spécialement aborder quelconque structure ou association existante).

À noter que je n'ai préalablement pas prévenu les fondateurs de FranceJS (j'avais brièvement discuté de l'idée il y a plusieurs années avec @vdeturckheim).

Mon idée serait d'ouvrir une discussion avec les membres du Slack et comprendre s'ils seraient favorables à migrer sur Discord (Il y a encore quelques années il y avait des débats entre les deux solutions.. Mais aujourd'hui la majorité des communautés de développeurs sont sur Discord).

Notre code de conduite étant flexible et ouvert nous pourrions faire les compromis nécessaire tant que ceux-ci sont bénéfiques à la communauté au sens large.

> **Note** L'évènement Paris.js possède aussi un Discord. Je pense que ce serait là aussi cohérent de l'intégrer dans la communauté.

Évidemment je suis conscient que cela **n'aboutira probablement pas**. Mais je pense sincèrement que ne pas en parler ou proposer l'idée serait une erreur (n'importe le résultat).

❤️

**Comment by Xstoudi** [comment]
Il suffit de leur envoyer le lien du CoC, non ?
Si Paris.js souhaite avoir son channel dans la catégorie events je n'y vois pas d'objection.

Sur le principe je ne suis pas contre, à vrai dire il suffit de leur transmettre le CoC et chacun rejoint comme il le souhaite. Par contre, concernant les compromis éventuels que tu mentionnes : ça sera du cas par cas et tant qu'il n'y a pas de proposition c'est compliqué de se prononcer.

**Comment by fraxken** [comment]
Oui je cloture 😉
