### ISSUE TITLE
Création d'un logo

### ISSUE THREAD

**Issue by fraxken** [ES-Community/Code-of-conduct#28]
Il serait sympa d'avoir un logo (qui s'inspire de la base du logo ES6 ou JS) avec des initiales ou des couleurs française (truc dans le genre).

Avez vous des propositions ?

**Comment by fraxken** [comment]
Merci de laisser votre vote pour le futur logo de la communauté (crée par amatart). Les logos sont sur la branche "logo" dans le répertoire "logo".

Merci d'indiquer lequel des logos vous préférer. 

Personnellement j'aime la version 1.

**Comment by izanagi1995** [comment]
Je vote pour la version 5 :)

**Comment by matt16016** [comment]
La v3

**Comment by Xstoudi** [comment]
V6 et V8 dans mon cas. J'aime pas mal la petite sensation de relief en plus sur les autres.

**Comment by nolanrigo** [comment]
La v5 est ma préférée

**Comment by Westixy** [comment]
v3 ou v5

**Comment by ILikeBananas** [comment]
V6

**Comment by tiyodev** [comment]
V5 pour moi

**Comment by tiyodev** [comment]
ou v8 ^^

**Comment by Vavaballz** [comment]
V1 ou V5

**Comment by valh1996** [comment]
Hello v6 ou v8 pour ma part :)

**Comment by BNedry** [comment]
v1

**Comment by Ravaniss** [comment]
V5 pour ma part ! :D

**Comment by Purexo** [comment]
v0 pour ma part :p

https://cdn.discordapp.com/attachments/157206345949511680/321034432733773824/logo_es_community.jpg

**Comment by fraxken** [comment]
Je clôture les votes. La V5 gagne ! Merci à amatart pour son boulot (à noter que j'ai toutes les versions format .PDS vectoriel).
