### ISSUE TITLE
Bot discord

### ISSUE THREAD

**Issue by fraxken** [ES-Community/Code-of-conduct#33]
Bonjour chère communauté, 

Je soumets cette issue dans l'objectif de discuter l'intégration d'un Bot sur le discord (en accord avec le futur guide de contribution officiel). 

L'idée est d'intégrer un Bot développé en NodeJS (code open source) qui apportera de nouvelles possibilités à la communauté. Voici quelques idées : 

- Commandes ( gestion des rôles, par exemple ).
- Succès ( gérer des succès avec un système de points par exemple ).
- Badge membre ( Image générée dynamiquement par le bot avec vos succès etc... ).

N'hésitez donc pas à faire votre retour sur vôtre position (et proposer des idées si vous en avez).

**Note** : Nous avons déjà un début de code sur le gitlab (en attente de transition vers le github).

Cordialement,
Thomas

**Comment by Xstoudi** [comment]
Suivi et retransmission des Twitters intéressants.

**Comment by ILikeBananas** [comment]
Suivit des personnes de la communauté pour les streams par exemple.
Le système de badge pourrai être sympa j'avoue, mais il y en aura beaucoup à gérer.

**Comment by Xstoudi** [comment]
Suivi des changement sur tc39/proposals

**Comment by fraxken** [comment]
Le repo du bot à été mis à jour : 

- Possède maintenant une fonctionnalité pour suivre les tweets originaux des membres de la communauté Node.JS et ECMAScript (encore en test). 

Ce que j'ai en tête pour la suite : 

- Comme proposé par @Xstoudi et dans la même ligne que Tweeter ( Un streaming des commits fait sur un ou plusieurs **github** ). L'ont pourrait donc faire un salon "TC39#proposals" qui retranscrirait tout les commits. 

> A voir les solutions possible 

- Un système de lien rapide vers la doc MDN et Node.JS (et plus plus tard).

Par exemple : 
```
!doc node http
!doc js Set
```

Cela pourrait permettre l'envoi des liens vers la documentation plus rapidement (par le bot).

Voilà n'hésitez pas si vous avez encore des idées :) 

Cordialement,
Thomas
