### ISSUE TITLE
Groupe LinkedIN ?

### ISSUE THREAD

**Issue by fraxken** [ES-Community/Code-of-conduct#35]
Bonjour chère communauté,

Je me disais qu'il pourrait être intéressant d'avoir un groupe LinkedIn pour démarcher notre communauté auprès de développeur(s) Node.JS professionnel (En partie des personnes comme nous). Et dans un second temps pouvoir offrir aux éventuelles sociétés un moyen de prendre contact ou bien même laisser des offres d'emploi (CDI ou Freelance).

Qu'en pensez-vous ?

Cordialement,
Thomas

**Comment by Xstoudi** [comment]
C'est tout bénef, complètement pour :)

**Comment by tiyodev** [comment]
Idem je suis pour, un bon point pour le profil Linkedin

**Comment by nolanrigo** [comment]
Je suis complètement pour l'idée 👍

**Comment by Westixy** [comment]
Pour
Mais la facilité d'entrée dans la communauté ne risque pas de transformer le groupe en une sorte de "page fb" des gens qui aime le js (c'est peut être l'idée en fait mais ca risque moins d'intéresser les entreprise du coup)

**Comment by fraxken** [comment]
@Westixy 

C'est effectivement une possibilité. Cela ne change néanmoins pas grand-chose pour notre communauté (dans le sens discord). Je pense que la réponse se trouve dans la mise en place de processus et de règles comme nous avons su le faire jusqu'à maintenant. 

Pour le moment je ne vois pas aussi loin. L'objectif est de nous ouvrir une porte de communication vers un réseau professionnel. Attendons-donc d'avoir un premier pas pour pouvoir savoir comment nous positionner tout en satisfaisant au possible l'intégralité des membres de la communauté.

Comme pour le code de conduite, l'expérience nous amènera certainement à changer nos choix pour une meilleure approche.

**Comment by fraxken** [comment]
Voilà le groupe à été crée (en respect avec les délai imposé par le code de contribution) et ayant récolté une majorité d’avis positif.

https://www.linkedin.com/groups/8626096

La structure (textes et images) reste encore à faire. J'ai invité la plupart des membres de la communauté que j'avais dans ma liste de contacts.

Bref n'hésitez pas à faire un feedback sur ses points là (ont à le temps).

**Comment by Xstoudi** [comment]
Je close, hésitez pas à ré-ouvrir une issue en cas de remarque, avis, etc.
