### ISSUE TITLE
Catégories Discord

### ISSUE THREAD

**Issue by Xstoudi** [ES-Community/Code-of-conduct#36]
Salutations !

Selon les règles de la communauté, je vous soumets à validation, commentaires, etc, la hiérarchie suivante contient le titre du channel et sa description, et donnera par la suite lieux à une PR :

* Général - Catégorie générale
    * Annonces - Annonces des administrateurs
    * Présentation - Présentations des nouveaux arrivants
    * Blabla - Discussions générales
* Développement - Catégorie développement
    * ECMAScript - ES, son passé, son présent, son avenir
    * Node.js - La vie
    * Front - Tout ce qui touche aux frameworks fronts
    * Node-native - CPP, Rust avec les bindings natifs Node.js
* Base de données - Catégorie base de données
    * Systèmes [de gestion de base de données] SQL - Les classiques
    * MongoDB - Le célébrissime
    * RethinkDB - L'agréable
    * Redis - Le performant
    * old_database - Archive
* Administration système - Catégorie adminsys
    * Linux - Tous les systèmes Linux
    * Windows - Un problème avec votre système ?
    * Docker - Le déploiement avec Docker
    * old_system - Archive
* Autres
    * Liens - Liens utiles
    * Jeux - Venez jouer !
    * Gif - Images funs
    * Bot - Bot de la communauté
    * Video-blog - Projet de vidéo-blogs
    * Vocal - Communication par écrit des salons vocaux
    * old_others - Archive

J'attends vos remarques, commentaires, idées.

**Comment by Xstoudi** [comment]
Les salons d'archive `old_` devraient être rangés dans une catégorie "Archives" ?

**Comment by nolanrigo** [comment]
La structure est cohérente + les channels `old_` dans une catégorie Archives, ok pour moi :+1:

**Comment by fraxken** [comment]
Il vaudrait peut-être mieux renommer les salons en questions " Others " non ? Ont risque d'avoir pas mal de besoins non couvert (notamment sur la zone BDD). Cela nous évite aussi d'avoir une section "archive" pas forcément très utile.

**Comment by Xstoudi** [comment]
"autres" alors. C'est pas faux effectivement.

**Comment by Purexo** [comment]
Maintenant que c'est sortie, je signal que les catégories ne sont pas des channel, par conséquent on ne peux pas écrire dedans, dons pas besoin de `old_` pour éviter les chan doublons

**Comment by Purexo** [comment]
Ah et aussi, il ne devrait pas avoir de clash sur les noms c'est vraiment 2 entités a part

**Comment by nolanrigo** [comment]
Cela dit, je mettrais le channel `Liens` dans la catégorie général :thinking:

**Comment by Xstoudi** [comment]
Changements appliqués au serveur Discord.
