### ISSUE TITLE
Changement du salon #bot

### ISSUE THREAD

**Issue by Xstoudi** [ES-Community/Code-of-conduct#40]
Renommer le salon #bot en #esc-git et le déplacer dans la catégorie "Général".

**Comment by fraxken** [comment]
Je propose qu'on passe le salon en "privé" aussi avec un rôle pour y accéder. Comme pour Tweets.

**Comment by Xstoudi** [comment]
J'ai modifié #es-git en #esc-git pour être plus précis.

**Comment by RomainLanz** [comment]
Hello 👋 

Pourquoi pas le renommer simplement en `logs`? Sachant qu'il pourrait contenir par la suite d'autre log que simplement celui de Github.

**Comment by Xstoudi** [comment]
On le renommera à ce moment-là ^^

**Comment by fraxken** [comment]
@Xstoudi Du coup quel est l'état de la demande ? 

Il faudrait statuer sur un nom définitif ( logs me semblent une bonne proposition). Néanmoins cela peut-être sous a un vote si nécessaire.

**Comment by Purexo** [comment]
Pour ma part "logs" je trouve ça bien
