### ISSUE TITLE
Ajout d'une règle pour la présentation

### ISSUE THREAD

**Issue by Westixy** [ES-Community/Code-of-conduct#45]
Afin d'éviter les présentations trop light du style 
`Yo c'est Kevin et j'aime le JS :D`
Je voudrais proposer une modification sur la partie "Critères pour entrer sur le discord" vu que le but d'une présentation est de se présenter (sans déc) dans le but que les autres puisse avoir 2-3 infos sur la personne.
Bref, j'aimerai ajouter aux critères d'au moins mettre l'âge (ou un indice de l'age si ça pose probleme a certains), depuis combien de temps la personne fait du JS (peut très bien etre 2 semaines) et d'autres infos qui pourrait être pertinentes.

Le but n'est pas de juger mais de pouvoir en savoir un peu plus sur la personne.

Qu'en pensez-vous ?

**Comment by Xstoudi** [comment]
Ca serait bien d'avoir une proposition concrète de laquelle on puisse discuter.

**Comment by Xstoudi** [comment]
Le nom me paraît accessoire, on se réfère aux membres par leur pseudos et ils peuvent se faire appeler par leur prénom et/ou nom en changeant de nom d'utilisateur sur le serveur.

Par contre j'ajouterais :
* Profile Github/Gitlab/Bitbucket

**Comment by Xstoudi** [comment]
Tu peux faire une PR avec une modification du code de conduite pour soumettre ça à l'approbation des mentors.

**Comment by fraxken** [comment]
#47 La PR !

**Comment by RomainLanz** [comment]
Je clos pour éviter de split la conversation vu qu'une PR est open.
