### ISSUE TITLE
Archive de plusieurs projets (répertoires git)

### ISSUE THREAD

**Issue by fraxken** [ES-Community/Code-of-conduct#55]
J'aimerai archiver les répertoires GIT (projets) suivant: 

- https://github.com/ES-Community/blog-jekyll-archived
- https://github.com/ES-Community/ESOS

Conformément à notre code de conduite (et code de contribution) je soumets donc la demande à la communauté (et aux mentors) pour approbation.

**Comment by fraxken** [comment]
@Purexo Le répertoire cactus-dark est t'il toujours nécessaire ? (Si non, il faudrait aussi l'archiver).

**Comment by Purexo** [comment]
Tant qu'il est utilisé pour le Blog de la communauté, il sera nécessaire.

Il est séparé du Repo du Blog car c'est un fork, et ça me permet de le tenir à jour simplement à l'occasion.

**Comment by fraxken** [comment]
Discuté et confirmé avec les mentors. Les deux répertoires ont bien été archivé !
