### ISSUE TITLE
Ajouter un salon "job"

### ISSUE THREAD

**Issue by AlexandreMalaj** [ES-Community/Code-of-conduct#57]
Au vu de toutes les demandes de postes que je reçoit sur LinkedIn, je me suis dit qu'il serait intéressant de créer un salon pour partager les annonces.
Vu que pour ma part je les refuses tous et que les recruteurs ont du mal a trouver des candidats, je trouve dommage qu'on ne puisse pas partager pour ceux qui pourrait être à l'écoute d'opportunité !

Bien sûr, le but n'est pas de devenir un relais pour les recruteurs !

J'avais pensé dans un premier tant a un regroupement de channel sous le nom "job" avec des sous salon du type #front, #back, #leadDev, etc ... Mais il y a aussi une deuxième approche avec le même système utilisé avec le channel #liens : [Front], [Back], [leadDev], etc

**Comment by Purexo** [comment]
Je suis pas contre la création d'un channel #jobs avec une nomenclature similaire à celle du channel #liens . Après reste à voir dans quelle catégorie on le met. Et détailler cette nomenclature

**Comment by Purexo** [comment]
je dirais

```md
**[ Orientation du poste ] - [ langage/techno (si possible avec les émoji) ] - Intitulé du poste**

Description rapide (missions proposés, lieu, nom de la boite, rémunération...)

Lien de l'annonce / Contact
```

**Comment by fraxken** [comment]
Je ne suis pas spécialement pour ou contre la proposition. Néanmoins je ne sais pas si la mise en place de ce salon ne demandera pas l'ajout de plusieurs nouvelles règles au sein du code conduit.

Aussi, le salon doit-il être librement accessible ? Ou peut-être avec un rôle comme pour tweets ?

**Comment by Purexo** [comment]
Accès restreint à `@Community` me semble bien ;-)

Je trouve pas ça pratique (et ça donne beaucoup de taf pour rien) de lier des chans à des rôles.

Si des gens veulent pas des notifs sur certains chan, il y a tout ce qu'il faut sur Discord pour ça.

**Comment by fraxken** [comment]
Salon intégré au discord !
