### ISSUE TITLE
Premier volet de changement pour les salons

### ISSUE THREAD

**Issue by fraxken** [ES-Community/Code-of-conduct#58]
Bonjour,

Cette proposition a pour objectif la modification de plusieurs salons (et catégories) sur le discord. Elle vise les catégories "administration système" et "Base de données" (cette proposition ne vise donc pas la modification des autres catégories).

**Les modifications**

- Suppression du salon Windows pour inactivité (le salon autres fera largement l'affaire).
- Suppression complète de la catégorie Base de données (avec l'intégralité de ses salons).
- Modification du titre de catégorie "Administration Système" pour "Système et Database"
- Ajout d'un salon "Database" dans la catégorie Système et Database.

**Explication des modifications** 
Les salons présents dans la catégorie Base de données sont très peu actif. Sachant qu'il nous est impossible de créer des salons pour chaque BDD existante, il vaut mieux partir sur l'idée de n'avoir qu'un seul salon pour gérer l'intégralité des problèmes liés aux bases de données.

La catégorie administration système est la plus apte à recevoir ce nouveau salon. (De plus cela aura peut-être pour effet de renforcer l'activité au sein de cette catégorie).

En attente de vos retours !

**Comment by Purexo** [comment]
Il y a un seul truc qui me dérange la dedans. C'est la suppression des messages de coulants de la suppression des chan.

Je propose une catégorie Archive ou on déplace ces chan (et probablement d'autres dans le future) et qui sera en lecture seule bien sûr.

**Comment by nolanrigo** [comment]
Personnellement la suppression des anciens messages ne me dérange. et la création d'une catégorie archive ne ferait qu'alourdir la navigation.

**Comment by fraxken** [comment]
Je pense la même chose que Nolan. Il suffira de transformer le salon bdd/autres en database. Les autres salons ne comporte que très peu de messages finalement:

- mongodb: 250 messages
- systemes-sql: 150 messages
- rethinkdb: 70 messages
- redis: 39 messages

Le salon autres de database comporte tout de même 2566 messages ! (Donc il me paraît logique qu'il soi choisi pour le transition).

**Comment by fraxken** [comment]
Merci à vous ! Le changement est en place.
