### ISSUE TITLE
Nettoyage des rôles

### ISSUE THREAD

**Issue by fraxken** [ES-Community/Code-of-conduct#62]
J'écris cette demande dans l'objectif de remettre à zéro la gestion des rôles au sein de la communauté. Le constat est que la plupart des rôles ne sont pas spécialement nécessaires et n'ont bien souvent aucune réelle valeur (Sans parler de la difficulté de garder les rôles en question à jour sur les membres de la communauté).

> Cet demande de changement n'impactera pas les rôles de base: Fondateur, Mentor, Communauté.

Les rôles Twitter et Logs ne seront pas non plus impactés par cet demande (Rôles d'accès à des salons privés).

L'objectif est de laisser plus de place à d'éventuel futur changement et/ou évolution autour des rôles. Peut-être par exemple pouvoir mieux fédérer/certifier certains rôles.

**Comment by Xstoudi** [comment]
Pour moi, très honnêtement, le système de rôles n'est pas nécessaire du tout. Ou alors il est nécessaire de le garder très générique pour ne pas s'y perdre.
A mon sens, une bonne répartition des sujets par salon est beaucoup plus efficace et beaucoup plus simple à gérer que des rôles.

**Comment by Purexo** [comment]
Pour ma part je trouve que tu ne va pas assez loin dans la réflexion.

Je rejoins @Xstoudi . On peux très bien supprimer tout les rôles (sauf Fondateur, Mentor, Communauté évidement) même Twitter et Logs on peux les tejs il y a pas besoin que ces salons soient privé sincèrement (et si les gens ne veulent pas ce faire spam par ce type de chan, ils suffit pour eux de mute les chans en question 😉)

Mais je crois bien avoir déjà dis ça dans une autre issue.

**Comment by tiyodev** [comment]
Je pense la même chose,les rôles Fondateur, Mentor, Communauté suffisent amplement. C'est plus simple à gérer et je vois aucun chan qui doit être privé.

**Comment by Westixy** [comment]
Pour aussi.
Sinon pour garder l'idée du qui maitrise quoi on pourrait ajouter une fonctionnalité au bot qui servirai a definir des domaines de compétences pour chaque personnes et ajouter une commande pour chercher des membres qui maitrise un domaine.
Ex :
- `!mastery add HTML CSS ES5+` ajoute les compétences a soit meme
- `!mastery add @garry HTML CSS ES5+` ajoute les compétences a garry
- `!mastery search HTML CSS` list les personnes qui ont les compétences HTML **et**/**ou** CSS
- `!mastery remove CSS`  supprime les compétences a soit meme
- `!mastery list`  liste toutes les compétences 
- `!mastery create Vue`  cree la compétence Vue

Je suis peut etre parti un peu loin mais c'est une idée a voire

**Comment by Xstoudi** [comment]
C'était l'idée initiale à laquelle je m'oppose pour une raison très simple : c'est très inexhaustif.

**Comment by Purexo** [comment]
Tout comme faire un listing sous forme de rôle (on aura jamais une liste complète de toutes les techno quelle que sois la méthode), je trouve l'argument léger pour le coup.

Après la vrai question à ce poser c'est : Quel est l’intérêt d'assigner des connaissances à des membres ? Et cet intérêt est il suffisant pour qu'on y cherche un substitut ou on s'en fous.

En tout cas pour le moment, tout le monde à l'air d'accord pour dire que ça met trop de bazars dans les rôles pour rien.

**Comment by Xstoudi** [comment]
Bah en l'occurence c'est pas léger vu que j'ai jamais prétendu être en faveur du listing sous forme de rôles.

L'intérêt le plus flagrant c'est de pouvoir chercher à qui s'adresser en cas de problème.

La vraie question c'est de savoir comment c'est utilisé depuis qu'on la mis en place ?
La réponse c'est que ça a jamais été utilisé vu que les rôles ont le "allow anyone to mention this role" sur OFF. Donc visiblement, tel quel, ça rajoute des badges aux gens sans apporter quoi que ce soit derrière.

**Comment by AlexandreMalaj** [comment]
En parlant de ce système de rôle, qui de mon point de vue n'apporte pas grand chose, il y a plusieurs chose qui rentre en compte.
Comme l'a dit @Purexo, la première question est : 
- Quel est l’intérêt d'assigner des connaissances à des membres ?
**La question doit être absolument posé !**
Pour ma part je répondrai : pour connaitre un minimum les membres !

Si intérêt il y a :
- Savoir comment ça a été utilisé depuis la mise en place (@Xstoudi)

A partir de là il y a plusieurs possibilités, mais Discord nous offre-t-il l'opportunité de mettre en place ce que l'on/vous souhaiter-ait/iez ! Ce point est aussi important !

Dans mon idée, j'avais en tête le channel **#présentation**.
Le channel en lui même est intéressant, mais le gros problème est que les nouveaux arrivant ne connaissent  pas les personnes dans la communauté mis à part les dernières présentations affichées. Reste à savoir si l'arrivant a envie de se taper tout le channel de présentation ! 👎 

Si c'est une "communauté" il faut que les nouveaux puissent se faire une idée des personnes présentes. Se connaitre quoi ! Du moins... un minimum bordel !

J'avais donc pensé à pouvoir "reprendre" les présentations déjà écritent pour les "lier" avec les personnes (en note ?). Le problème reste : est-ce que Discord nous permettrait de réaliser cela ? De plus, cela est-il vraiment envisageable et possible ?

Avec cette approche, on oubli donc clairement les rôles (mis à part ceux déjà évoqués), et sont remplacés par une "présentation" (voir si possible une plus succincte). Car au fond, je ne pense pas que les personnes recherchent quelqu'un de spécifique mais écrivent juste leurs problèmes dans le bon canal et attendent une réponse.

Dans tous les cas, il faut répondre au deux questions citées plus haut si on veut que le sujet avance ! 😃

**Comment by DraftProducts** [comment]
Pour rejoindre l'idée de @Westixy l'idée du bot me plait bien mais plutôt sous forme de réactions, j'avais fait ça sur d'autres serveurs et c'était plutôt sympa 
Un message par couleur avec le titre qui corresponds et les icones correspondant

**Comment by Purexo** [comment]
@DraftProducts j'arrive pas trop à comprendre ton truc. Est-ce que tu peux expliquer un peu plus en détail comment ça fonctionne ?

**Comment by DraftProducts** [comment]
Dans ce style là mais avec les icones de chaque framework, langages ect
![image](https://user-images.githubusercontent.com/29425008/43660397-2a55f392-975f-11e8-861b-cb012a644d2e.png)

Je penses que les catégories pourrais être en fonction des couleurs comme ceci : 
 - Langages
 - Databases
 - Frameworks Js
 - Outils
ect...

**Comment by tiyodev** [comment]
Pour répondre à la question : Quel est l’intérêt d'assigner des connaissances à des membres ?

je pense qu'on est tous plus ou moins d'accord, ça sert uniquement à mieux connaitre les membres de la commu.

Donc pour moi le mieux serait d'avoir un visuel au niveau des présentations sur les compétences de chacun. Ce que propose @DraftProducts peut être pas mal.

**Comment by DraftProducts** [comment]
Le problème étant qu'une note appartient à un membre avec comme cible un autre membre et je ne penses pas d'un bot du discord puisses accéder aux infos perso d'un membre

**Comment by DeltaEvo** [comment]
J'ai pas compris ce que tu essaye d'avancer @DraftProducts, une note ?

**Comment by DraftProducts** [comment]
J'avais donc pensé à pouvoir "reprendre" les présentations déjà écritent pour les "lier" avec les personnes (en note ?). Le problème reste : est-ce que Discord nous permettrait de réaliser cela ? De plus, cela est-il vraiment envisageable et possible ?

**Comment by DeltaEvo** [comment]
Ce n'est pas possible avec un bot, les note sur un utilisateurs ne sont pas globale à tout les membres, donc seul le propriétaire du compte peux mettre des notes
Nb: il peux y avoir un moyen si l'utilisateur nous délègue un accès a son api (oauth), mais c'est un peu contraignant pour pas grand chose
Je pense que t'as pas besoin de lier ça, la recherche Discord fais bien l'affaire

**Comment by DraftProducts** [comment]
C'est pas moi qui ai dit ça... @DeltaEvo c'est toi

**Comment by DeltaEvo** [comment]
Non @DraftProducts j'ai seulement cité @AlexandreMalaj pour lui repondre

**Comment by DraftProducts** [comment]
Ah autant pour moi j'avais pas compris

**Comment by fraxken** [comment]
Merci d'éviter de partir dans des monologues à trois kilomètres de la demande initiale (cela n'aide vraiment pas). Si vous avez des idées particulières pour la suite, le système de demande est ouvert ! (A faire sur le repo es_bot pour les évolutions du bot).

Je vais mettre en place la demande initiale sur le discord (puisqu'elle semble majoritairement acceptée).

**Comment by fraxken** [comment]
La demande est désormais en place !
