### ISSUE TITLE
Rétrogradation de plusieurs membres inactifs

### ISSUE THREAD

**Issue by fraxken** [ES-Community/Code-of-conduct#63]
Je demande la rétrogradation de plusieurs membres inactifs au sein de la communauté (suppression du rôle "communauté"). Les personnes en question ne seront pas exclu de la communauté et pourront toujours venir se (re) présenter sans problème.

La liste des membres:

Nom | messages (nb) | Inscription | avg msg / jour | nb jours depuis dernier msg
-- | -- | -- | -- | -- |
Matteokocken | 255 | 27/05/2017 | 0,555 | 156
BNedry | 248 | 31/08/2016 | 0,333 | 349
Killians06 | 209 | 28/02/2017 | 0,333 | 355
Nopoza973 | 80 | 28/09/2017 | 0,222 | 235
Raulel | 32 | 24/10/2017 | 0,111 | 259
Mafiatoss | 39 | 08/11/2017 | 0,111 | 170
Nonimad | 29 | 09/12/2017 | 0,111 | 233
Okazari | 14 | 18/03/2017 | 0 | 501
stropitek | 1 | 23/08/2017 | 0 | 343
D4ryl00 | 30 | 13/09/2017 | 0 | 312
(Psy) Pierre.G | 10 | 21/09/2017 | 0 | 313
Yoha | 5 | 24/09/2017 | 0 | 311
dodo021 | 1 | 07/10/2017 | 0 | 298
araylos | 5 | 16/11/2017 | 0 | 257
Greggen | 6 | 02/12/2017 | 0 | 224
zak | 5 | 03/12/2017 | 0 | 236
Saya | 3 | 22/02/2018 | 0 | 157
MisterT | 2 | 23/02/2018 | 0 | 159
APPRC | 1 | 02/03/2018 | 0 | 152
Bloody | 2 | 20/03/2018 | 0 | 134
minoo | 2 | 26/03/2018 | 0 | 128
Léamsi | 1 | 18/04/2018 | 0 | 105

À noter que les personnes de cette liste peuvent se manifester avant la date butoir de rétrogradation (sept jours min).

**Comment by Xstoudi** [comment]
`minoo` a demandé à garder son rôle sur Discord : il est actif en lecture.
Quand je l'ai averti du clean, `araylos` m'a dit la même chose, il est actif en lecture.

**Comment by stropitek** [comment]
Hello
Je souhaiterais également garder mon rôle dans la communauté.

Je n'étais pas actif car je n'avais jusque maintenant pas réussi à installer discord sur Linux. Mais c'est depuis peu réglé!

**Comment by fraxken** [comment]
Les membres en question ont bien été exclu du rôle "communauté". (En dehors des personnes qui ont demandé à rester).
