### ISSUE TITLE
Nouveau Channel destiné au partage et aux avis

### ISSUE THREAD

**Issue by DraftProducts** [ES-Community/Code-of-conduct#64]
Bonsoir,
J'écris cette demande dans l'objectif de créer un channel permettant de partager et de recevoir un avis sur une quelconque création graphique. Que ce soit du WebDesign du dessin vectoriel ou autre.

Je comprends bien que cette communauté est surtout axé dans le développement et plus précisément dans le Javascript mais je penses qu'un channel de ce genre pourrait réellement être un ajout positif au partage et aux conseils car je sais par expérience qu'il est toujours utile d'avoir un autre point de vu sur sa création !

Ce channel pourrait simplement être dans la catégorie `Autres` mais si il prends plus d’ampleur au sein de la communauté il pourrait même faire partie de la catégorie `Général` !

Merci à ceux qui auront pris le temps de lire cette issue.

Et pensez bien à mettre un 👍ou un 👎 pour indiquer si cette idée vous a plu ou si vous la trouvez complètement 💩

**Comment by tiyodev** [comment]
Je ne suis pas contre un channel de ce type mais il faut le restreinte à des créations en relations avec le web ou le dev en général.

**Comment by Xstoudi** [comment]
Perso je trouve ça intéressant.
Tu peux créer une PR pour proposer son intégration au CoC, on commentera et on en débattra.

**Comment by DraftProducts** [comment]
Je suis tout à fait d'acc

**Comment by DraftProducts** [comment]
Je suis tout à fait d'accord avec @tiyodev le contenu doit rester dans le domaine du développement web par contre je n'ai pas vraiment compris ton point de vu @Xstoudi le but étant d'avoir un avis et des conseills sur une réalisation donc je vois pas pourquoi il y aurait un ponpage visuel ou un vol de contenu ?

**Comment by Xstoudi** [comment]
Le but peut-être d'avoir des avis, des conseils ou simplement d'exposer son taf.
Et dans ce dernier cas, si quelqu'un poste un contenu qui n'est pas de lui, comme dit plus haut, ça représente une infraction grave.

**Comment by DraftProducts** [comment]
Ok je l'avait pas vu sous cet angle ! @Xstoudi

**Comment by DraftProducts** [comment]
Donc ? @Xstoudi 
on fait quoi pour ce channel ?

**Comment by Purexo** [comment]
Je pense que ça peut partir en PR.

A rappeler que pour partager le taf d'un autre, #lien #blabla ou #autre font très bien l'affaire, donc pas d'excuse.

**Comment by DraftProducts** [comment]
Mais c'est pas pour partager le taff d'un autre --'

**Comment by LightDiscord** [comment]
@DraftProducts je pense que @Purexo parlait de le rappeler dans la PR pour le noter dans le CoC

**Comment by Xstoudi** [comment]
Je close l'issue, je te laisse PR.

**Comment by antoineneff** [comment]
J'arrive un peu tard mais du coup on peut pas partager des créations autres que les notres ? Notamment pour parler d'un style qu'on aime, de ce dont on aimerait s'inspirer ou qqch comme ça ?

**Comment by WebD-EG** [comment]
Je crois que si on mentionne l'auteur de la création, cela ne poserait pas trop de problèmes? Non?

**Comment by DraftProducts** [comment]
@antoineneff si tu nomme l'auteur ou un style oui vu que c'est un salon de partage !

**Comment by Xstoudi** [comment]
Comme le prévoit la PR de DraftMan, si vous citez l'auteur il n'y a effectivement pas de problème.
