### ISSUE TITLE
Rework rôles principaux

### ISSUE THREAD

**Issue by Xstoudi** [ES-Community/Code-of-conduct#66]
Cette proposition intervient dans la linée de l'issue #62 .

Actuellement, dans la liste des membres, les membres de la Communauté ainsi que les Mentors possèdent la même couleurs et leurs noms sont mélangés dans la liste des utilisateurs.

Intervient alors la premier proposition : 
Mettre en évidence les membres du mentorat en activant la séparation dans la liste. Changer leur couleur ne me paraît pas forcément nécessaire, mais c'est aussi une idée.

Ma seconde proposition concerne la création d'un grade "honorifique" qui serait attribuée à la discrétion des mentors aux membres se distinguant par leur implication dans la vie de la communauté, par le biais de l'aide qu'ils apportent aux autres membres ou de la qualité de leur travail, sans pour autant qu'ils ne deviennent des modérateurs.
J'ai en tête quelques pseudos qui sont aujourd'hui de mon point de vue de véritables piliers.
Idem, dans le cas où cette proposition vous intéresse, il serait à déterminer si leur pseudo serait séparé des autres membres et/ou s'ils auraient une autre couleur.

Je vous laisse donner votre avis sur le sujet dans cette issue et d'ici quelques temps, si les réponses sont favorables, je créerai une PR dans le but de soumettre tout ça aux autres mentors.

**Comment by fraxken** [comment]
- 1. Je suis assez neutre sur le sujet, si cela peut améliorer les choses et que tout le monde est d'accord alors pourquoi pas.
- 2. Tu me prends de court ^^ ! Moi et Romain nous en discutions il y a encore pas longtemps, donc je suis plutôt pour cet apport.

**Comment by Westixy** [comment]
mmmh distinguer les membres de la communauté ? c'est pas quelque chose dont on avait déjà parlé avec le titre de mentor à la place de modérateur où l'idée de la communauté était de rester sur un pied d'égalité ?
Du coup pour moi je suis plutôt contre l'idée de distinguer plus les membres de la communauté avec les mentors. De meme que pour le titre honorifique qui ne ferai qu'accentuer cette différence chez les membres. Ce statut n'a donc pas d'utilité de mon point de vue.

**Comment by DraftProducts** [comment]
Personnellement je suis tout à fait **pour** ta première proposition pour cette certification qui d'après moi permet d'apporter de la valeur à un conseil une aide. Ce qui pourrait être sympathique serais aussi une certification dans les domaines spécifiques mais ça risquerait de rendre la gestion des rôles impossible et risquerait aussi de devenir n'importe quoi.

Pour ce qui est de l'attribution des rôles en fonction des messages je suis plutôt **contre** étant donnée que le niveau d'un développeur serais comparé au nombre de messages envoyés lors des discussions. Et un bot discord appelé Mee6 permet de faire cela et à mon goût les communautés avant cette fonctionnalité augmente considérablement le nombre de messages mais les explications ainsi que les messages et les avais perdent en qualité ainsi qu'en argumentation car le but n'est plus d'aider les autres développeurs mais de voir son rank augmenter pour soit disant gagner en valeur au sein de la communauté.
Je penses donc que les fondateurs, administrateurs sont à même d'attribuer des rôles aux plus méritants et aux développeurs expérimentés !

**Comment by Xstoudi** [comment]
Je reviens sur le message de Nopoza : Je ne souhaite personnellement pas que le grade honorifique soit associé à un nombre de message pour deux raisons :
* Ca encourage la quantité, pas la qualité
* Ca limite cette récompense aux membres très actifs alors que l'intérêt de se titre serait de récompenser les personnes dont la présence est qualitative, qu'ils postent 10 messages par semaine ou 200.

**Comment by RemyTinco** [comment]
Yep, je suis d'accord avec toi, c'était juste une illustration pour la transparence. Cela peut être un nombre de recommandation. Par exemple, tu m'as aidé à résoudre un problème, je te _recommande_ et au bout de 30 recommandations tu deviens "_Honorifique_"

**Comment by Xstoudi** [comment]
J'ai  supprimé les doublons du dernier message de DraftMan ^^

**Comment by DraftProducts** [comment]
Dsl Xstoudi j'étais sur tel et j'étais dans la cambrousse donc la 4G est pas top...

**Comment by nolanrigo** [comment]
Je suis piur faire une signification (et non pas parce que, pour l'instant, ça me concerne). Mais dans le cas ou un nouveau a besoin d'aide au niveau de la communauté (son intégration, médiation de conflit) ça serait cool qu'ils aient une liste direct admins / mentors. 
Pour la deuxième proposition, je suis complètement pour, bien que je ne mettrais pas de distinction de couleur

**Comment by DeltaEvo** [comment]
Pour la première proposition, je n'ai pas vraiment d'avis, comme le soulève Nolan ça semble utile pour les nouveaux membres surtout quand ils n'ont pas encore de repères au niveau de la communauté, donc en effet pourquoi pas :smile: 

Pour le deuxième bien que ce soit seulement honorifique, je me demande si ça ne va pas apparaitre comme une separation de la communauté, une categorie intermediaire entre le membre et le mentor :thinking:, après sinon si ça se fait je pense que la selection automatique est à bannir car ce n'est pas fiable (Le nombre de message ne veux rien dire, et "voter" pour les autres me semble vraiment bancale car la personne qui se fait aidé n'est pas vraiment capable de savoir si la solution donnée est "bonne" [Entendez par la si elle va resoudre son problème seulement à court terme où non])

**Comment by RomainLanz** [comment]
Hello,

Je pense que le problème qu'on a principalement lié au nommage des rôles.
C'est pour cela que je proposerais cette modification.

- Le rôle `Mentors` est renommé en `Modo`, il garde la même couleur et n'est pas séparé.
- Le nouveau rôle `Honorifique` est nommés `Mentors`, il a une couleur différente mais n'est pas séparé.

Je propose ce changement pour plusieurs raisons.

1. Le Mentors est présenté comme un modérateur, que ce soit sur le Discord ou écrit dans le CoC.
2. Le titre honorifique ressemble à ce que doit faire un Mentor (au sens litéral).

**Comment by Purexo** [comment]
C'est effectivement un facteur de confusion. c'était pas gênant tant que tout les mentors étaient modo. Mais la il va peut être falloir éclaircir tout ça.

**Comment by RomainLanz** [comment]
Mes propositions sont aussi réfléchies.

Il n'y a pas de raison de séparer les membres dès Modérateur, Mentors ou Fondateur, nous sommes tous membres au final. Avois une couleur différente pour les Mentors permet tout de même de savoir qu'on parle à un Mentors et pas à un simple membre de la communauté (plusieurs personnes ont dit que ceci serait intéressant).

Concernant les Modérateurs, il n'y a aucune utilité de les séparer, que ce soit niveau couleur ou dans la liste des membres. Ce sont juste des membres qui ont accès à des fonctionnalités d'administration si nécessaire.

A savoir qu'un Modérateur ou Fondateur peut-être Mentors.. ou non.

**Comment by Xstoudi** [comment]
Tout d'abord, je crois que nous n'avons pas la même description du grade de mentor (honorable). Le but du grade est simplement de récompenser un membre, pas de l'exposer comme le mec qui répond aux questions sur le Discord.

En somme, la couleur fait office de récompense, mais il n'y a effectivement pas de raison de les séparer des autres membres.

Concernant les modérateurs, actuels mentors : la séparation intervient pour faciliter leur repérage par les membres de la communauté en cas de besoin. La couleur intervient notamment pour ne pas porter à confusion avec les honorables.

**Comment by Xstoudi** [comment]
Sachant que pour le coup, la définition d'un honorable est importante puisque dans mon cas, de mémoire, il doit y avoir deux membres qui peuvent y prétendre.

**Comment by Purexo** [comment]
J'aime toujours pas l'idée de séparer les modérateurs des membres.

**Comment by Westixy** [comment]
je propose de creer un commentaire par point a voter histoire de pouvoir mettre au claire ce qui doit être mis en place ou ranger dans le tiroir.
- Modification du nom des modérateurs (actuels mentors) en "Modérateur"
- Ajouter un rôle "honorifique"
- Séparer les modérateurs des membres dans la liste
- Changer la couleur des modérateurs
- Si le rôle "honorifique" est accepté, donner une couleur différente à ce rôle
- Si le rôle "honorifique" est accepté, lui donner le nom de "Mentor" (à valider)

**Comment by DraftProducts** [comment]
Perso je suis pour tous ces points à par pour séparer les membres et là dessus je rejoins @Purexo un simple changement de couleur devrait suffire !

**Comment by fraxken** [comment]
Il faudrait organiser une petite conf audio pour mieux se comprendre sur les idées de chacun (On ne risque pas d'aboutir par écrit). Éventuellement séparer en plusieurs demandes si cela est possible.

**Comment by Xstoudi** [comment]
En l'occurence j'ai motivé la demande de mon côté.
Certains proposent des "contre-projets" mais il ne sera simplement pas possible de satisfaire tout le monde.

Autant le dire, en ce moment j'ai clairement pas le temps de support' la PR et de défendre un truc plus loin que ce que j'ai fait dans mes différents messages sur l'issue.

Du coup je close l'issue, mais si vous souhaitez faire un vocal et discuter d'une éventuelle PR, faites-vous plaisir :)
