### ISSUE TITLE
Ajout d'un nouveau rôle (et un nouveau salon) "Débutant"

### ISSUE THREAD

**Issue by fraxken** [ES-Community/Code-of-conduct#70]
Hello ! 

Cette demande a pour objectif d'ajouter un nouveau rôle **Débutant** ainsi qu'un salon du même nom dans la section **Développement**.

Les cibles de ce nouveau rôle seront majoritairement: 

- Les jeunes
- Les débutants (sous-entendus les moins expérimentés ayant des difficultés pour s'orienter dans l'apprentissage des bases).

Les objectifs seront de pouvoir mieux s'adapter et aider les débutants au sein d'un salon dédié. Les membres ne voulant pas être dérangé par ce genre de discussions pourront simplement rendre "muet" le salon en question !

Ceci devrait aussi permettre une meilleure accessibilité de la communauté pour les moins expérimentés (et inciter les moins confiants à poser plus de questions).

Les membres de la communauté sont bien évidemment autorisés à répondre au sein du salon **Débutant** (néanmoins les réponses n'étant pas sérieuse seront prohibées).

**Comment by Purexo** [comment]
Why not,

Par contre j'ai peur que ça finisse en bureau des pleurs en mode

> J'arrive pas à faire X avec Y langage / contexte, qui peut m'aider ?

Et que ça finisse en mode grafikart.

**Comment by fraxken** [comment]
Ce n'est pas non plus l'objectif. À voir aussi avec le temps si nous devons ajouter des règles au code de conduite pour être plus clair sur le comportement nécessaire :)

**Comment by Purexo** [comment]
Je me doute bien. j’avertis juste de la dérive qui risque de découler du channel.

**Comment by fraxken** [comment]
Salon et rôle ajouté ! Merci à tous (les mentors discuteront des débutants)
