### ISSUE TITLE
Renommer le channel #nodeschool

### ISSUE THREAD

**Issue by nolanrigo** [ES-Community/Code-of-conduct#78]
Hello,

le channel `#nodeschool` avait été créé parce qu'il était le "premier" événement qu'on a fait en communauté.

Cependant, il y a pléthore de meetups dans les grandes villes et on vient souvent discuter de ceux-ci dans ce channel, à défaut d'avoir le choix.

C'est pour cela que j'aimerais bien renommer le channel en `#meetup`.

Des avis ?

**Comment by fraxken** [comment]
Totalement d'accord ! Je suis pour.

**Comment by nolanrigo** [comment]
Je me suis posé la question si on devrait le faire.
J'en suis venu à la conclusion qu'`insomni-hack` était un événement annuel avec un objectif / des discussions bien spécifique et justifiait d'un channel dédié.

**Comment by Xstoudi** [comment]
Oui !

**Comment by RomainLanz** [comment]
Done!
