### ISSUE TITLE
Ce que doit logger #logs

### ISSUE THREAD

**Issue by Purexo** [ES-Community/Code-of-conduct#91]
Comme a dit @fraxken in https://github.com/ES-Community/Code-of-conduct/pull/90#issuecomment-642278637_

Je propose qu'on passe en revue ensemble ce qui est loggé dans ce canal, et qu'on ce mette d'accord sur ce qui devrait être enlevé et sur ce qui serait intéressant d'ajouter.

**Comment by targos** [comment]
De mon côté j'ai mute le canal et j'utilise le système de notifications de GitHub

**Comment by Purexo** [comment]
![image](https://user-images.githubusercontent.com/5005154/84599622-a0c5a180-ae73-11ea-86d3-9599eefb0e12.png)
![image](https://user-images.githubusercontent.com/5005154/84599632-b2a74480-ae73-11ea-90d8-b50f289b71e2.png)

Au final, pas tant d'event que ça :
- Issue comments
- Pull requests (tout les events possible de celles-ci)
- Pull request reviews
- Pushes
- Releases
- Repositories 
- Stars

Une question que je me pose, a-t-on vraiment besoin de ce canal ?

**Comment by Purexo** [comment]
Sondage rapide sur l'usage du canal #logs
Réagissez avec :
- 👍 si vous l'utilisez
- 👎 si vous ne l'utilisez pas

**Comment by Purexo** [comment]
Veille discussion. même si peu l'utilisent. Ce canal est utilisé de façon inteligente.
Il restera donc en place comme il est.

Une fois la politique d'archivage mise en place, j'ouvrirai une autre PR pour déplacer logs dedans afin qu'il reste accessible sans pour autant prendre de la place dans une catégorie alors qu'il n'est pas regardé par la commu mais par les admins.
