### ISSUE TITLE
Netoyage des chans + politiques d'archivage

### ISSUE THREAD

**Issue by Purexo** [ES-Community/Code-of-conduct#95]
Je met ça en issue pour le moment, le temps que la v2 du code of conduct soit validé pour que ce ne soit pas trop le bazar.

Comme indiqué dans https://github.com/ES-Community/Code-of-conduct/pull/93 je trouve que l'on commence à avoir trop de canaux.

# 1. Ajouter une catégorie archive
Je n'aime pas la suppression pure et simple des canaux, on devrait ajouter une catégorie pour y placer les canaux archivé. ils y seront en lecture seule pour tout le monde.

# 2. Canaux à archiver
- #battledev
- #insomni-hack (je pense que ces 2 channels peuvent être fusionnés avec meetup)
- #logs : cf https://github.com/ES-Community/Code-of-conduct/issues/91 il n'est pas utilisés, et pour ceux qui veulent des notifs ben github / rss / webhook mais pas sur ce discord, etc.
- #tweets : j'ai pas fais d'étude sur l'usage, mais le bot est down depuis octobre 2018...
- #giveaway : au pire on le réactivera le temps d'un prochain giveaway si besoin.
- #design : au final ce canal ne sers plus trop à ce qu'il devrait à savoir le partage de création graphique, et fait maintenant doublons avec #front

Et au passage, déplacer le canal #vocal vers la catégorie `VOCAL`

**Comment by Purexo** [comment]
J'ai peut être été un peu agressif pour les 2 premiers canaux, n'hésitez pas à donner votre avis, ajouter des canaux qui vous semblerez inutiles.

@fraxken @Xstoudi 
Des petites stats sur l'utilisation des canaux pourrait être pas mal pour ce faire une idée !
Par canal :
- nombre de message total
- nombre de message moyen par jours
- nombre de message moyen par jours sur les 3 derniers mois. découpé au mois, puis à la semaine
Et même chose, mais au nombre de participant unique par jours.

Amusez vous bien à calculer ces indicateurs 😘 !

**Comment by Mesteery** [comment]
* #batteldev :
  * Nombre de messages totales : **203**
  * Nombre de messages moyen par jours : **~0.86** (premier message : 14 mars 2020, dernier message : 5 novembre 2020, 236 jours d'intervalles)
  * Nombre de messages moyen par jours : **~0.86** (14 mars 2020 - 5 novembre 2020 : 236 jours d'intervalles)
  * Nombre de messages moyen par jours sur les 3 derniers mois : **~0.45** (15 août 2020 - 5 novembre 2020, 37 messages, 82 jours d'intervalles)

C'est tout ce que je peux fournir avec une simple recherche Discord (ça prend du temps quand même)

**Comment by Xstoudi** [comment]
C'est normal, c'est un channel d'event, prochaine édition dans deux semaines.

**Comment by Purexo** [comment]
PR créé
